# ========= PROD PROFILE =========
server.port=8080

# MySQL (set real values via env vars / secrets)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/user_service?useSSL=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

# Safer defaults for prod
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Actuator - restrict exposure in prod
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

info.app.name=User Service
info.app.profile=prod

# JWT (set via env vars in prod)
app.jwt.secret-base64=${JWT_SECRET_BASE64:CHANGE_ME}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:1800000}