spring.application.name=user-service

# Default profile (override with --spring.profiles.active=dev|prod)
spring.profiles.default=dev

# JSON (ISO) timestamps
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
